//JYJLLT
//10-26-16

#include <stdio.h>
#include <stdlib.h>

#include <errno.h> //error check
#include <string.h> //string

#include <fcntl.h> //open
#include <unistd.h> //close
#include <sys/stat.h> //umask

//generates random int by reading in 4 bytes from /dev/random
int randomInt() {

  int *randInt = (int *)malloc(4);
  int randfile = open("/dev/random", O_RDONLY);
  read(randfile,randInt,4);

  int i = *randInt;
  free(randInt);
  close(randfile);

  return i;

}

int main() {

  umask(0000);

  /*int fd;
  fd = open("testfile", O_CREAT, 0666);
  close (fd);*/

  int arr[10];
  int arr2[10];
  int i;

  //populates an array with 10 random numbers generated by your random function (print out each value)
  printf("Generating random numbers:\n");
  printf("arr = ");
  for ( i=0 ; i<10 ; i++) {
    int randInt = randomInt();
    arr[i]=randInt;
    printf("%d \n",arr[i]);
  }
  printf("\n");

  //writes the array to a file
  printf("Writing numbers to file...\n");
  int fd=open("testfile",O_CREAT |O_WRONLY,0644);
  int written = write(fd,arr ,40);
  close(fd);

  //reads that file into a different array
  printf("Reading numbers from file...\n");
  int fd2=open("testfile",O_RDONLY,0444);
  read(fd2,arr2,40);
  close(fd2);

  //prints out the contents of the second array to verify the random numbers are the same from step 1
  printf("Verification that written values were the same:\n");
  printf("arr2 = ");
  for ( i=0 ; i<10 ; i++) {
    printf("%d \n",arr2[i]);
  }
  printf("\n");

  return 0;

}
